# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cities.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cities.proto',
  package='gisdatascience',
  syntax='proto2',
  serialized_pb=_b('\n\x0c\x63ities.proto\x12\x0egisdatascience\"\x83\x02\n\tCity_prop\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0b\n\x03lat\x18\x02 \x02(\x02\x12\x0b\n\x03lon\x18\x03 \x02(\x02\x12\x0f\n\x07\x63ountry\x18\x04 \x02(\t\x12\x12\n\npopulation\x18\x05 \x02(\x05\x12\x32\n\x07isocods\x18\x06 \x03(\x0b\x32!.gisdatascience.City_prop.ISOcode\x1aR\n\x07ISOcode\x12\x0c\n\x04\x63ode\x18\x01 \x02(\t\x12\x39\n\x04type\x18\x02 \x01(\x0e\x32%.gisdatascience.City_prop.ISOcodeType:\x04ISO2\"!\n\x0bISOcodeType\x12\x08\n\x04ISO2\x10\x00\x12\x08\n\x04ISO3\x10\x01\"1\n\x06\x43ities\x12\'\n\x04\x43ity\x18\x01 \x03(\x0b\x32\x19.gisdatascience.City_prop')
)



_CITY_PROP_ISOCODETYPE = _descriptor.EnumDescriptor(
  name='ISOcodeType',
  full_name='gisdatascience.City_prop.ISOcodeType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ISO2', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ISO3', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=259,
  serialized_end=292,
)
_sym_db.RegisterEnumDescriptor(_CITY_PROP_ISOCODETYPE)


_CITY_PROP_ISOCODE = _descriptor.Descriptor(
  name='ISOcode',
  full_name='gisdatascience.City_prop.ISOcode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='gisdatascience.City_prop.ISOcode.code', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='gisdatascience.City_prop.ISOcode.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=175,
  serialized_end=257,
)

_CITY_PROP = _descriptor.Descriptor(
  name='City_prop',
  full_name='gisdatascience.City_prop',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='gisdatascience.City_prop.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lat', full_name='gisdatascience.City_prop.lat', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lon', full_name='gisdatascience.City_prop.lon', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='country', full_name='gisdatascience.City_prop.country', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='population', full_name='gisdatascience.City_prop.population', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isocods', full_name='gisdatascience.City_prop.isocods', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_CITY_PROP_ISOCODE, ],
  enum_types=[
    _CITY_PROP_ISOCODETYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=292,
)


_CITIES = _descriptor.Descriptor(
  name='Cities',
  full_name='gisdatascience.Cities',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='City', full_name='gisdatascience.Cities.City', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=294,
  serialized_end=343,
)

_CITY_PROP_ISOCODE.fields_by_name['type'].enum_type = _CITY_PROP_ISOCODETYPE
_CITY_PROP_ISOCODE.containing_type = _CITY_PROP
_CITY_PROP.fields_by_name['isocods'].message_type = _CITY_PROP_ISOCODE
_CITY_PROP_ISOCODETYPE.containing_type = _CITY_PROP
_CITIES.fields_by_name['City'].message_type = _CITY_PROP
DESCRIPTOR.message_types_by_name['City_prop'] = _CITY_PROP
DESCRIPTOR.message_types_by_name['Cities'] = _CITIES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

City_prop = _reflection.GeneratedProtocolMessageType('City_prop', (_message.Message,), dict(

  ISOcode = _reflection.GeneratedProtocolMessageType('ISOcode', (_message.Message,), dict(
    DESCRIPTOR = _CITY_PROP_ISOCODE,
    __module__ = 'cities_pb2'
    # @@protoc_insertion_point(class_scope:gisdatascience.City_prop.ISOcode)
    ))
  ,
  DESCRIPTOR = _CITY_PROP,
  __module__ = 'cities_pb2'
  # @@protoc_insertion_point(class_scope:gisdatascience.City_prop)
  ))
_sym_db.RegisterMessage(City_prop)
_sym_db.RegisterMessage(City_prop.ISOcode)

Cities = _reflection.GeneratedProtocolMessageType('Cities', (_message.Message,), dict(
  DESCRIPTOR = _CITIES,
  __module__ = 'cities_pb2'
  # @@protoc_insertion_point(class_scope:gisdatascience.Cities)
  ))
_sym_db.RegisterMessage(Cities)


# @@protoc_insertion_point(module_scope)
